/**
 * Phase 1 curated seed bank (spec §7: ship with a solid static seed bank to
 * de-risk launch; AI generation backfill lands in Phase 2).
 * 54 questions: 6 topics × 3 difficulties × 3 each. Expand per topic/difficulty
 * via POST /questions/seed idempotency or the Phase 2 generation worker.
 */
interface SeedQ {
  topic: string;
  subtopic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  type: 'mcq' | 'short_answer' | 'code';
  prompt: string;
  options?: string[];
  correct_answer: string;
  explanation: string;
}

export const SEED_QUESTIONS: SeedQ[] = [
  // ── ml-basics ──────────────────────────────────────────────────────────
  { topic: 'ml-basics', subtopic: 'concepts', difficulty: 'easy', type: 'mcq',
    prompt: 'What is supervised learning?',
    options: ['Learning from labeled examples', 'Learning without any data', 'Memorizing test answers', 'Random weight initialization'],
    correct_answer: 'Learning from labeled examples',
    explanation: 'Supervised learning trains on input–output pairs (labels) to predict outputs for new inputs.' },
  { topic: 'ml-basics', subtopic: 'concepts', difficulty: 'easy', type: 'mcq',
    prompt: 'Which task is a classification problem?',
    options: ['Predicting house prices', 'Detecting spam vs not spam', 'Forecasting temperature', 'Estimating delivery time'],
    correct_answer: 'Detecting spam vs not spam',
    explanation: 'Classification assigns discrete labels (spam/not spam); the others predict continuous values (regression).' },
  { topic: 'ml-basics', subtopic: 'workflow', difficulty: 'easy', type: 'mcq',
    prompt: 'Why do we split data into train and test sets?',
    options: ['To train faster', 'To measure generalization on unseen data', 'To use less memory', 'To satisfy legal requirements'],
    correct_answer: 'To measure generalization on unseen data',
    explanation: 'The test set simulates new data, revealing whether the model learned patterns or just memorized training examples.' },
  { topic: 'ml-basics', subtopic: 'overfitting', difficulty: 'medium', type: 'mcq',
    prompt: 'Training accuracy is 99% but validation accuracy is 72%. What is happening?',
    options: ['Underfitting', 'Overfitting', 'Data leakage into training', 'Correct convergence'],
    correct_answer: 'Overfitting',
    explanation: 'A large train–validation gap means the model memorized training noise instead of generalizable patterns.' },
  { topic: 'ml-basics', subtopic: 'regularization', difficulty: 'medium', type: 'mcq',
    prompt: 'What does L2 regularization do?',
    options: ['Removes all bias terms', 'Penalizes large weights to reduce overfitting', 'Increases the learning rate', 'Shuffles the dataset'],
    correct_answer: 'Penalizes large weights to reduce overfitting',
    explanation: 'L2 adds λ·Σw² to the loss, discouraging overly large weights that typically encode noise.' },
  { topic: 'ml-basics', subtopic: 'metrics', difficulty: 'medium', type: 'short_answer',
    prompt: 'Name the technique that reuses a model trained on a large dataset as a starting point for a related task.',
    correct_answer: 'transfer learning',
    explanation: 'Transfer learning fine-tunes pretrained representations, needing far less labeled data for the new task.' },
  { topic: 'ml-basics', subtopic: 'bias-variance', difficulty: 'hard', type: 'mcq',
    prompt: 'A model has high bias. Which change is most appropriate?',
    options: ['Add stronger regularization', 'Increase model capacity / add features', 'Remove training data', 'Decrease the learning rate to zero'],
    correct_answer: 'Increase model capacity / add features',
    explanation: 'High bias means systematic underfitting — the model is too simple, so capacity or better features help.' },
  { topic: 'ml-basics', subtopic: 'validation', difficulty: 'hard', type: 'mcq',
    prompt: 'Why can repeated tuning on the same validation set be misleading?',
    options: ['It corrupts the training data', 'The validation set becomes an implicit training set, optimism bias grows', 'It always improves test accuracy', 'GPUs overheat'],
    correct_answer: 'The validation set becomes an implicit training set, optimism bias grows',
    explanation: 'Each tuning decision leaks information; keep a held-out test set touched once for an honest estimate.' },
  { topic: 'ml-basics', subtopic: 'optimization', difficulty: 'hard', type: 'short_answer',
    prompt: 'In one or two words: what optimizer adds momentum-corrected adaptive per-parameter learning rates and is the default choice for most deep learning?',
    correct_answer: 'adam',
    explanation: 'Adam combines momentum with RMSProp-style adaptive rates and works well out of the box.' },

  // ── statistics ─────────────────────────────────────────────────────────
  { topic: 'statistics', subtopic: 'descriptive', difficulty: 'easy', type: 'mcq',
    prompt: 'Which measure is most robust to outliers?',
    options: ['Mean', 'Median', 'Range', 'Sum'],
    correct_answer: 'Median',
    explanation: 'The median depends on rank order, so extreme values barely move it, unlike the mean.' },
  { topic: 'statistics', subtopic: 'probability', difficulty: 'easy', type: 'mcq',
    prompt: 'Two events are independent when…',
    options: ['They cannot co-occur', 'P(A and B) = P(A)·P(B)', 'They share outcomes', 'One causes the other'],
    correct_answer: 'P(A and B) = P(A)·P(B)',
    explanation: 'Independence means knowing one outcome tells you nothing about the other; joint probability factorizes.' },
  { topic: 'statistics', subtopic: 'distributions', difficulty: 'easy', type: 'mcq',
    prompt: 'In a normal distribution, roughly what share of data falls within ±1 standard deviation?',
    options: ['50%', '68%', '95%', '99.7%'],
    correct_answer: '68%',
    explanation: 'The 68-95-99.7 rule: ~68% within one sigma, ~95% within two, ~99.7% within three.' },
  { topic: 'statistics', subtopic: 'inference', difficulty: 'medium', type: 'mcq',
    prompt: 'A 95% confidence interval for a mean is [4.1, 5.9]. The correct interpretation is…',
    options: ['95% of data lies in [4.1, 5.9]', '95% of such constructed intervals would contain the true mean', 'The true mean is 5.0 with 95% probability', 'The p-value is 0.95'],
    correct_answer: '95% of such constructed intervals would contain the true mean',
    explanation: 'Frequentist CIs describe long-run coverage of the procedure, not the probability that this interval holds the truth.' },
  { topic: 'statistics', subtopic: 'testing', difficulty: 'medium', type: 'mcq',
    prompt: 'A p-value of 0.03 means…',
    options: ['3% chance the null hypothesis is true', 'Assuming the null, 3% chance of results this extreme', '97% chance the alternative is true', 'The effect size is 0.03'],
    correct_answer: 'Assuming the null, 3% chance of results this extreme',
    explanation: 'The p-value is P(data this extreme | H₀), not P(H₀ | data) — a common misreading.' },
  { topic: 'statistics', subtopic: 'bayes', difficulty: 'medium', type: 'short_answer',
    prompt: 'Name the theorem that updates P(hypothesis|data) from the prior, likelihood, and evidence.',
    correct_answer: 'bayes theorem',
    explanation: "Bayes' theorem: posterior ∝ likelihood × prior, normalized by evidence." },
  { topic: 'statistics', subtopic: 'regression', difficulty: 'hard', type: 'mcq',
    prompt: 'Heteroscedasticity in linear regression violates which assumption?',
    options: ['Linearity', 'Constant error variance', 'Independence of features', 'Normality of features'],
    correct_answer: 'Constant error variance',
    explanation: 'Heteroscedasticity = non-constant residual variance; standard errors become unreliable.' },
  { topic: 'statistics', subtopic: 'causality', difficulty: 'hard', type: 'mcq',
    prompt: 'Simpson’s paradox shows that…',
    options: ['Correlation equals causation', 'Aggregated trends can reverse within subgroups', 'P-values are always wrong', 'Randomization is useless'],
    correct_answer: 'Aggregated trends can reverse within subgroups',
    explanation: 'A confounder (e.g. subgroup size/severity) can flip the apparent direction of an effect when pooled.' },
  { topic: 'statistics', subtopic: 'mle', difficulty: 'hard', type: 'short_answer',
    prompt: 'What three-letter method picks parameters maximizing the probability of the observed data?',
    correct_answer: 'mle',
    explanation: 'Maximum Likelihood Estimation (MLE) chooses θ maximizing L(θ) = P(data|θ).' },

  // ── neural-networks ────────────────────────────────────────────────────
  { topic: 'neural-networks', subtopic: 'perceptron', difficulty: 'easy', type: 'mcq',
    prompt: 'What does an activation function do?',
    options: ['Initializes weights', 'Adds non-linearity so networks learn complex patterns', 'Splits the dataset', 'Normalizes labels'],
    correct_answer: 'Adds non-linearity so networks learn complex patterns',
    explanation: 'Without non-linear activations, stacked layers collapse into a single linear transform.' },
  { topic: 'neural-networks', subtopic: 'activations', difficulty: 'easy', type: 'mcq',
    prompt: 'ReLU(x) equals…',
    options: ['1/(1+e^-x)', 'max(0, x)', 'tanh(x)', 'x²'],
    correct_answer: 'max(0, x)',
    explanation: 'ReLU passes positive values and zeroes negatives — cheap and effective against vanishing gradients.' },
  { topic: 'neural-networks', subtopic: 'training', difficulty: 'easy', type: 'mcq',
    prompt: 'Backpropagation computes…',
    options: ['Optimal weights directly', 'Gradients of the loss w.r.t. parameters via the chain rule', 'The best architecture', 'Feature importances'],
    correct_answer: 'Gradients of the loss w.r.t. parameters via the chain rule',
    explanation: 'Backprop efficiently applies the chain rule layer by layer; an optimizer then steps the weights.' },
  { topic: 'neural-networks', subtopic: 'loss', difficulty: 'medium', type: 'mcq',
    prompt: 'Best loss for multi-class classification with softmax outputs?',
    options: ['Mean squared error', 'Categorical cross-entropy', 'Hinge loss always', 'L1 loss'],
    correct_answer: 'Categorical cross-entropy',
    explanation: 'Cross-entropy pairs with softmax to penalize confident wrong predictions proportionally.' },
  { topic: 'neural-networks', subtopic: 'regularization', difficulty: 'medium', type: 'mcq',
    prompt: 'Dropout regularizes by…',
    options: ['Dropping the learning rate', 'Randomly zeroing activations during training', 'Removing test samples', 'Pruning the dataset'],
    correct_answer: 'Randomly zeroing activations during training',
    explanation: 'Dropout prevents co-adaptation; at inference all units are active (scaled appropriately).' },
  { topic: 'neural-networks', subtopic: 'cnn', difficulty: 'medium', type: 'short_answer',
    prompt: 'What three-letter layer type shares weights across spatial positions to detect local patterns in images?',
    correct_answer: 'cnn',
    explanation: 'Convolutional layers reuse small filters across the image, giving translation equivariance with few parameters.' },
  { topic: 'neural-networks', subtopic: 'optimization', difficulty: 'hard', type: 'mcq',
    prompt: 'Why do very deep plain networks degrade (higher train error than shallower ones)?',
    options: ['Too much data', 'Vanishing/exploding gradients make deep stacks hard to optimize', 'GPUs are too slow', 'Labels are wrong'],
    correct_answer: 'Vanishing/exploding gradients make deep stacks hard to optimize',
    explanation: 'Repeated multiplication through layers shrinks or blows up gradients; skip connections (ResNets) fix this.' },
  { topic: 'neural-networks', subtopic: 'normalization', difficulty: 'hard', type: 'mcq',
    prompt: 'Batch normalization primarily helps by…',
    options: ['Increasing batch size', 'Stabilizing layer input distributions so higher learning rates work', 'Removing the need for data', 'Encrypting activations'],
    correct_answer: 'Stabilizing layer input distributions so higher learning rates work',
    explanation: 'Normalizing mini-batch statistics smooths optimization; it also has a mild regularization side effect.' },
  { topic: 'neural-networks', subtopic: 'init', difficulty: 'hard', type: 'short_answer',
    prompt: 'Name the initialization scheme designed for ReLU networks that samples weights with variance 2/fan_in.',
    correct_answer: 'he initialization',
    explanation: 'He (Kaiming) init preserves activation variance through ReLU layers, avoiding dead starts.' },

  // ── deep-learning ──────────────────────────────────────────────────────
  { topic: 'deep-learning', subtopic: 'rnn', difficulty: 'easy', type: 'mcq',
    prompt: 'What is the key idea of a recurrent neural network?',
    options: ['Processing sequences via a hidden state passed across time steps', 'Ignoring order in data', 'Using only convolutions', 'Training without gradients'],
    correct_answer: 'Processing sequences via a hidden state passed across time steps',
    explanation: 'RNNs carry a hidden state forward, letting later steps depend on earlier context.' },
  { topic: 'deep-learning', subtopic: 'attention', difficulty: 'easy', type: 'mcq',
    prompt: 'Attention mechanisms let a model…',
    options: ['Train without data', 'Weigh the relevance of different input positions dynamically', 'Skip evaluation', 'Compress weights to zero'],
    correct_answer: 'Weigh the relevance of different input positions dynamically',
    explanation: 'Attention computes relevance scores so each output can focus on the most useful inputs.' },
  { topic: 'deep-learning', subtopic: 'transformers', difficulty: 'easy', type: 'mcq',
    prompt: 'What does positional encoding add to a Transformer?',
    options: ['More training data', 'Order information, since self-attention is permutation-invariant', 'Extra labels', 'Dropout noise'],
    correct_answer: 'Order information, since self-attention is permutation-invariant',
    explanation: 'Self-attention sees a set, not a sequence — positional encodings inject token order.' },
  { topic: 'deep-learning', subtopic: 'lstm', difficulty: 'medium', type: 'mcq',
    prompt: 'LSTMs handle long-range dependencies better than vanilla RNNs because…',
    options: ['They are smaller', 'Gating (input/forget/output) preserves gradients over long spans', 'They skip backprop', 'They use no parameters'],
    correct_answer: 'Gating (input/forget/output) preserves gradients over long spans',
    explanation: 'The cell state highway plus gates lets information (and gradients) flow across many steps.' },
  { topic: 'deep-learning', subtopic: 'gan', difficulty: 'medium', type: 'mcq',
    prompt: 'A GAN trains…',
    options: ['One network alone', 'A generator against a discriminator in a minimax game', 'Only on labeled pairs', 'Without any loss function'],
    correct_answer: 'A generator against a discriminator in a minimax game',
    explanation: 'The generator fools the discriminator while the discriminator gets better at detection — equilibrium yields realistic samples.' },
  { topic: 'deep-learning', subtopic: 'autoencoders', difficulty: 'medium', type: 'short_answer',
    prompt: 'What two-word model compresses inputs to a bottleneck and reconstructs them, useful for denoising and pretraining?',
    correct_answer: 'autoencoder',
    explanation: 'Autoencoders learn compact representations by minimizing reconstruction error through a bottleneck.' },
  { topic: 'deep-learning', subtopic: 'diffusion', difficulty: 'hard', type: 'mcq',
    prompt: 'Diffusion models generate data by…',
    options: ['Memorizing pixels', 'Iteratively denoising pure noise conditioned on a prompt', 'Sorting the dataset', 'Averaging all images'],
    correct_answer: 'Iteratively denoising pure noise conditioned on a prompt',
    explanation: 'Training reverses a gradual noising process; sampling applies the learned denoiser step by step.' },
  { topic: 'deep-learning', subtopic: 'efficient-attention', difficulty: 'hard', type: 'mcq',
    prompt: 'Standard self-attention scales how with sequence length n?',
    options: ['O(n)', 'O(n²) time/memory', 'O(log n)', 'O(1)'],
    correct_answer: 'O(n²) time/memory',
    explanation: 'Every token attends to every other token — the n×n attention matrix dominates long-context cost.' },
  { topic: 'deep-learning', subtopic: 'normalization', difficulty: 'hard', type: 'short_answer',
    prompt: 'Which normalization, standard in Transformers, normalizes across the feature dimension of each token independently of batch?',
    correct_answer: 'layer normalization',
    explanation: 'LayerNorm stabilizes per-token activations and works with variable batch sizes and sequence lengths.' },

  // ── llms ───────────────────────────────────────────────────────────────
  { topic: 'llms', subtopic: 'pretraining', difficulty: 'easy', type: 'mcq',
    prompt: 'Most LLMs are pretrained with which objective?',
    options: ['Next-token prediction', 'Image rotation', 'Manual rule writing', 'Sorting words alphabetically'],
    correct_answer: 'Next-token prediction',
    explanation: 'Causal language modeling — predict the next token — scales beautifully with data and compute.' },
  { topic: 'llms', subtopic: 'tokenization', difficulty: 'easy', type: 'mcq',
    prompt: 'Tokenization is…',
    options: ['Encrypting the model', 'Splitting text into model-consumable pieces (words/subwords)', 'Deleting stopwords', 'Translating languages'],
    correct_answer: 'Splitting text into model-consumable pieces (words/subwords)',
    explanation: 'Subword tokenizers (BPE/SentencePiece) balance vocabulary size against sequence length.' },
  { topic: 'llms', subtopic: 'prompting', difficulty: 'easy', type: 'mcq',
    prompt: 'Zero-shot prompting means…',
    options: ['No prompt at all', 'Asking the task with instructions but no examples', 'Training with zero data', 'Using zero parameters'],
    correct_answer: 'Asking the task with instructions but no examples',
    explanation: 'Zero-shot = instructions only; few-shot adds examples in the prompt.' },
  { topic: 'llms', subtopic: 'alignment', difficulty: 'medium', type: 'mcq',
    prompt: 'RLHF aligns models by…',
    options: ['Random initialization', 'Fine-tuning on human preference rankings via a reward model + RL', 'Removing all filters', 'Longer pretraining only'],
    correct_answer: 'Fine-tuning on human preference rankings via a reward model + RL',
    explanation: 'Human pairwise preferences train a reward model; PPO/DPO-style optimization steers the LLM toward preferred outputs.' },
  { topic: 'llms', subtopic: 'rag', difficulty: 'medium', type: 'mcq',
    prompt: 'RAG reduces hallucinations by…',
    options: ['Increasing temperature', 'Grounding generation in retrieved documents', 'Shortening outputs', 'Disabling sampling'],
    correct_answer: 'Grounding generation in retrieved documents',
    explanation: 'Retrieval-Augmented Generation fetches relevant passages and conditions the answer on them.' },
  { topic: 'llms', subtopic: 'decoding', difficulty: 'medium', type: 'short_answer',
    prompt: 'What sampling parameter (0–2) controls randomness: higher means more creative/diverse output?',
    correct_answer: 'temperature',
    explanation: 'Temperature rescales logits before sampling; 0 is greedy/deterministic, higher values diversify.' },
  { topic: 'llms', subtopic: 'context', difficulty: 'hard', type: 'mcq',
    prompt: '“Lost in the middle” refers to…',
    options: ['Models forgetting pretraining', 'Degraded use of information in the middle of long contexts', 'Tokenizer errors', 'GPU memory leaks'],
    correct_answer: 'Degraded use of information in the middle of long contexts',
    explanation: 'Long-context models attend best to the start/end; critical facts buried mid-context get underused.' },
  { topic: 'llms', subtopic: 'finetuning', difficulty: 'hard', type: 'mcq',
    prompt: 'LoRA fine-tunes efficiently by…',
    options: ['Retraining all weights', 'Training small low-rank adapters while freezing base weights', 'Deleting layers', 'Quantizing labels'],
    correct_answer: 'Training small low-rank adapters while freezing base weights',
    explanation: 'Low-Rank Adaptation injects trainable rank-r matrices, cutting trainable parameters by orders of magnitude.' },
  { topic: 'llms', subtopic: 'agents', difficulty: 'hard', type: 'short_answer',
    prompt: 'What four-letter paradigm interleaves model reasoning with tool/API calls to solve multi-step tasks?',
    correct_answer: 'tool use',
    explanation: 'Tool use (function calling) lets LLMs query APIs, run code, and browse — acting as agents.' },

  // ── evaluation ─────────────────────────────────────────────────────────
  { topic: 'evaluation', subtopic: 'classification-metrics', difficulty: 'easy', type: 'mcq',
    prompt: 'Accuracy is misleading when…',
    options: ['Classes are balanced', 'Classes are heavily imbalanced', 'The dataset is large', 'Features are normalized'],
    correct_answer: 'Classes are heavily imbalanced',
    explanation: 'Predicting only the majority class scores high accuracy while learning nothing — use precision/recall/F1.' },
  { topic: 'evaluation', subtopic: 'precision-recall', difficulty: 'easy', type: 'mcq',
    prompt: 'High recall with low precision means…',
    options: ['Few false negatives but many false alarms', 'Few false alarms but many misses', 'Perfect predictions', 'Random guessing'],
    correct_answer: 'Few false negatives but many false alarms',
    explanation: 'Recall catches most positives (few misses); low precision means many predicted positives are wrong.' },
  { topic: 'evaluation', subtopic: 'splits', difficulty: 'easy', type: 'mcq',
    prompt: 'Cross-validation primarily…',
    options: ['Speeds up training', 'Estimates performance robustly by rotating validation folds', 'Replaces testing', 'Encrypts data'],
    correct_answer: 'Estimates performance robustly by rotating validation folds',
    explanation: 'Averaging over folds reduces variance from any single lucky/unlucky split.' },
  { topic: 'evaluation', subtopic: 'roc', difficulty: 'medium', type: 'mcq',
    prompt: 'ROC-AUC of 0.5 indicates…',
    options: ['A perfect classifier', 'No discrimination (random-level)', 'Zero error', 'Infinite loss'],
    correct_answer: 'No discrimination (random-level)',
    explanation: 'AUC = probability a random positive outranks a random negative; 0.5 is chance.' },
  { topic: 'evaluation', subtopic: 'llm-eval', difficulty: 'medium', type: 'mcq',
    prompt: 'Why is exact-match scoring insufficient for open-ended LLM answers?',
    options: ['It is too slow', 'Correct answers can be phrased many valid ways', 'GPUs dislike strings', 'It needs labels'],
    correct_answer: 'Correct answers can be phrased many valid ways',
    explanation: 'Use rubric/LLM-judge or semantic-similarity scoring for generative outputs.' },
  { topic: 'evaluation', subtopic: 'ab-testing', difficulty: 'medium', type: 'short_answer',
    prompt: 'In online experiments, what is the group called that receives the existing baseline experience?',
    correct_answer: 'control',
    explanation: 'Control vs treatment comparison isolates the causal effect of the change.' },
  { topic: 'evaluation', subtopic: 'leakage', difficulty: 'hard', type: 'mcq',
    prompt: 'Target leakage happens when…',
    options: ['The model is too small', 'Training features contain information unavailable at prediction time', 'Labels are balanced', 'Learning rate is high'],
    correct_answer: 'Training features contain information unavailable at prediction time',
    explanation: 'Leaky features inflate offline metrics and fail in production — e.g. including post-outcome fields.' },
  { topic: 'evaluation', subtopic: 'calibration', difficulty: 'hard', type: 'mcq',
    prompt: 'A well-calibrated classifier with 80% confidence predictions is…',
    options: ['Correct 100% of the time', 'Correct ~80% of the time on those predictions', 'Always wrong', 'Unmeasurable'],
    correct_answer: 'Correct ~80% of the time on those predictions',
    explanation: 'Calibration aligns stated confidence with empirical frequency — critical for risk-sensitive decisions.' },
  { topic: 'evaluation', subtopic: 'offline-online', difficulty: 'hard', type: 'short_answer',
    prompt: 'What is the gap called when offline metrics improve but live A/B metrics do not (two words)?',
    correct_answer: 'offline online gap',
    explanation: 'Distribution shift, feedback loops, and metric misalignment cause the offline–online gap.' },
];
